name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
api: 1.13
api-version: 1.13
softdepend: [PlaceholderAPI, MineClans]
commands:
  classes:
    description: "Check information about the classes"
  bard:
    description: "Check information about the Bard class"
  archer:
    description: "Check information about the Archer class"
  rogue:
    description: "Check information about the Rogue class"
  miner:
    description: "Check information about the Miner class"
  