name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
api: 1.13
api-version: 1.13
softdepend: [PlaceholderAPI, MineClans]
commands:
  classes:
    aliases: [bard]